### ISSUE TITLE
FileNotFoundError subclass_scenario

### ISSUE THREAD

**Issue by nematollahsaeidi** [forderation/breast-cancer-retrieval#1]
when I run retrieval_sample.py, I get an error as "FileNotFoundError: [Errno 2] No such file or directory: 'subclass_scenario/test/400X/benign'" in line 21. How can I solve it? thanks

**Comment by forderation** [comment]
please refer to [README.MD](https://github.com/forderation/breast-cancer-retrieval#readme) using raw version [link](https://drive.google.com/drive/folders/1oQXs24X8BIA4CqllPUQTk4PWDdTbJREf?usp=sharing)

**Comment by emadsaeidi** [comment]
.thank you for your reply
 .I would like to read your paper to understand more details about the
implementations. if possible, send me the paper
.If I write a paper I will cite your work

Sincerely
Nemat

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/15/22,
03:19:40 AM
